// Copyright 2022 Var (@itsvar8)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define I2C1_SDA_PIN B9
#define I2C1_SCL_PIN B8

#define IS31FL3733_I2C_ADDRESS_1 IS31FL3733_I2C_ADDRESS_GND_GND

#define TAPPING_TOGGLE 2
#define DYNAMIC_MACRO_NO_NESTING
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD 
#define LEADER_PER_KEY_TIMING
#define LEADER_NO_TIMEOUT

#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#define NO_ACTION_ONESHOT
#define LAYER_STATE_8BIT
