LEADER_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
CAPS_WORD_ENABLE = yes
MIDI_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes

CONSOLE_ENABLE = no
DEBUG_ENABLE = no
COMMAND_ENABLE = no
TAP_DANCE_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
BACKLIGHT_ENABLE = no
